[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
DashTable = "1b08a953-4be3-4667-9a23-f0e2ba4deb9a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
