name = "Dashboards"
uuid = "9024f26f-ba4d-4e0a-965a-ad5b1da667aa"
authors = ["Alexandr Romanenko"]
version = "0.2.6"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.1"
DataStructures = "0.17.5"
HTTP = "0.8.6"
JSON = "0.21.0"
JSON2 = "0.3.1"
MacroTools = "0.5.1"
PlotlyBase = "0.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
